# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cdee6fa0fa7e1da02ff0c1d69efc18adde8e38999e9d87985212d196254cddbee398fb702fe2d463362ac46d7e0e9975186e7ea9ddd7725ae02ff93915524c71

test:
  secret_key_base: 5fcf8093bf40699433e856442292c49ac62bca9fcc5be20603bf0b829b76d4803b48c55bcd9834beaf28560332df9ebc9aa4baaa7333a5fdde7d9d76e7f3b1b9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
